"""initial schema

Creates users, sessions, hosted_zones, dns_records, and record_values with foreign keys
(ON DELETE CASCADE), unique and CHECK constraints, and indexes. Timestamps (UTCDateTime) and
value_json (JSONText) are stored as TEXT; see docs/DATABASE.md.

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 12:00:27.610206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('hosted_zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=253), nullable=False),
    sa.Column('zone_type', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("zone_type IN ('PUBLIC', 'PRIVATE')", name=op.f('ck_hosted_zones_zone_type')),
    sa.CheckConstraint('comment IS NULL OR length(comment) <= 1000', name=op.f('ck_hosted_zones_comment_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hosted_zones_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hosted_zones')),
    sa.UniqueConstraint('zone_id', name=op.f('uq_hosted_zones_zone_id'))
    )
    with op.batch_alter_table('hosted_zones', schema=None) as batch_op:
        batch_op.create_index('ix_hosted_zones_user_id_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_hosted_zones_user_id_name', ['user_id', 'name'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_sessions_user_id', ['user_id'], unique=False)

    op.create_table('dns_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hosted_zone_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=253), nullable=False),
    sa.Column('record_type', sa.String(length=8), nullable=False),
    sa.Column('routing_policy', sa.String(length=16), server_default=sa.text("'SIMPLE'"), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("record_type IN ('A', 'AAAA', 'CNAME', 'TXT', 'MX', 'NS', 'PTR', 'SRV', 'CAA', 'SOA')", name=op.f('ck_dns_records_record_type')),
    sa.CheckConstraint("routing_policy IN ('SIMPLE')", name=op.f('ck_dns_records_routing_policy')),
    sa.CheckConstraint('comment IS NULL OR length(comment) <= 1000', name=op.f('ck_dns_records_comment_length')),
    sa.CheckConstraint('ttl_seconds IS NULL OR (ttl_seconds >= 0 AND ttl_seconds <= 2147483647)', name=op.f('ck_dns_records_ttl_range')),
    sa.ForeignKeyConstraint(['hosted_zone_id'], ['hosted_zones.id'], name=op.f('fk_dns_records_hosted_zone_id_hosted_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dns_records')),
    sa.UniqueConstraint('hosted_zone_id', 'name', 'record_type', name=op.f('uq_dns_records_hosted_zone_id_name_record_type'))
    )
    with op.batch_alter_table('dns_records', schema=None) as batch_op:
        batch_op.create_index('ix_dns_records_hosted_zone_id_name', ['hosted_zone_id', 'name'], unique=False)
        batch_op.create_index('ix_dns_records_hosted_zone_id_record_type', ['hosted_zone_id', 'record_type'], unique=False)

    op.create_table('record_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('display_value', sa.Text(), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_record_values_position_non_negative')),
    sa.ForeignKeyConstraint(['record_id'], ['dns_records.id'], name=op.f('fk_record_values_record_id_dns_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_values')),
    sa.UniqueConstraint('record_id', 'position', name=op.f('uq_record_values_record_id_position'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_values')
    with op.batch_alter_table('dns_records', schema=None) as batch_op:
        batch_op.drop_index('ix_dns_records_hosted_zone_id_record_type')
        batch_op.drop_index('ix_dns_records_hosted_zone_id_name')

    op.drop_table('dns_records')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_id')
        batch_op.drop_index('ix_sessions_expires_at')

    op.drop_table('sessions')
    with op.batch_alter_table('hosted_zones', schema=None) as batch_op:
        batch_op.drop_index('ix_hosted_zones_user_id_name')
        batch_op.drop_index('ix_hosted_zones_user_id_created_at')

    op.drop_table('hosted_zones')
    op.drop_table('users')
    # ### end Alembic commands ###
